DROP TABLE doc_asn_appointment;
CREATE TABLE doc_asn_appointment (
  [Id] [int] IDENTITY(1,1) NOT NULL,
  [CreationTime] [datetime2](7) NOT NULL,
  [CreatorUserId] [bigint] NULL,
  [LastModificationTime] [datetime2](7) NULL,
  [LastModifierUserId] [bigint] NULL,
  [IsDeleted] [bit] NOT NULL,
  [DeleterUserId] [bigint] NULL,
  [DeletionTime] [datetime2](7) NULL,
  organizationId varchar(20)  NOT NULL,
  warehouseId varchar(20)  NOT NULL,
  asnNo varchar(20)  NOT NULL,
  appointmentNo varchar(20)  NOT NULL,
  vehicleNo varchar(20)  NOT NULL,
  asnAppStatus char(2)  NOT NULL,
  passCard varchar(20)  DEFAULT NULL,
  driver varchar(20)  DEFAULT NULL,
  dockNo varchar(50)  DEFAULT NULL,
  entranceTime datetime NULL DEFAULT NULL,
  leaveTime datetime NULL DEFAULT NULL,
  startUnloadTime datetime NULL DEFAULT NULL,
  endUnloadTime datetime NULL DEFAULT NULL,
  dockAssignmentTime datetime NULL DEFAULT NULL,
  broadCast char(1)  DEFAULT NULL,
  lockFlag char(1)  DEFAULT NULL,
  seqNo varchar(10)  DEFAULT NULL,
  startTime varchar(5)  DEFAULT NULL,
  operationTime int DEFAULT NULL,
  noteText text,
  udf01 varchar(500)  DEFAULT NULL,
  udf02 varchar(500)  DEFAULT NULL,
  udf03 varchar(500)  DEFAULT NULL,
  udf04 varchar(500)  DEFAULT NULL,
  udf05 varchar(500)  DEFAULT NULL,
  currentVersion int NOT NULL DEFAULT '100',
  oprSeqFlag varchar(65)  NOT NULL DEFAULT '2016',
  -- addWho varchar(40)  DEFAULT NULL,
  -- addTime datetime NULL DEFAULT NULL,
  -- editWho varchar(40)  DEFAULT NULL,
  -- editTime datetime NULL DEFAULT NULL,
  vehicleType varchar(10)  DEFAULT NULL,
  PRIMARY KEY (Id),
  INDEX auto_shard_key_organizationId (organizationId),
  INDEX I_DOC_ASN_APPOINTMENTS(organizationId,warehouseId,asnNo,appointmentNo,vehicleNo)
);



-- wms_ftest.doc_asn_container definition

DROP TABLE doc_asn_container;
CREATE TABLE doc_asn_container (
  [Id] [int] IDENTITY(1,1) NOT NULL,
  [CreationTime] [datetime2](7) NOT NULL,
  [CreatorUserId] [bigint] NULL,
  [LastModificationTime] [datetime2](7) NULL,
  [LastModifierUserId] [bigint] NULL,
  [IsDeleted] [bit] NOT NULL,
  [DeleterUserId] [bigint] NULL,
  [DeletionTime] [datetime2](7) NULL,
  organizationId varchar(20)  NOT NULL,
  warehouseId varchar(20)  NOT NULL,
  asnNo varchar(20)  NOT NULL,
  ctnNo varchar(20)  NOT NULL,
  ctnType char(2)  NOT NULL,
  ctnSize char(2)  NOT NULL,
  ctnSealNo1 varchar(10)  DEFAULT NULL,
  ctnSealNo2 varchar(10)  DEFAULT NULL,
  ctnGrossWeight decimal(18,8) NOT NULL,
  ctnFee decimal(24,8) DEFAULT NULL,
  chargeDate datetime NULL DEFAULT NULL,
  noteText text ,
  udf01 varchar(500)  DEFAULT NULL,
  udf02 varchar(500)  DEFAULT NULL,
  udf03 varchar(500)  DEFAULT NULL,
  udf04 varchar(500)  DEFAULT NULL,
  udf05 varchar(500)  DEFAULT NULL,
  udf06 varchar(500)  DEFAULT NULL,
  currentVersion int NOT NULL DEFAULT '100',
  oprSeqFlag varchar(65)  NOT NULL DEFAULT '2016',
  -- addWho varchar(40)  DEFAULT NULL,
  -- addTime datetime NULL DEFAULT NULL,
  -- editWho varchar(40)  DEFAULT NULL,
  -- editTime datetime NULL DEFAULT NULL,
  PRIMARY KEY (Id),
  INDEX auto_shard_key_organizationId (organizationId),
  INDEX I_DOC_ASN_CONTAINERS(organizationId,warehouseId,asnNo,ctnNo)
) ;








-- wms_ftest.doc_asn_details definition

DROP TABLE doc_asn_details
CREATE TABLE doc_asn_details (
  [Id] [int] IDENTITY(1,1) NOT NULL,
  [CreationTime] [datetime2](7) NOT NULL,
  [CreatorUserId] [bigint] NULL,
  [LastModificationTime] [datetime2](7) NULL,
  [LastModifierUserId] [bigint] NULL,
  [IsDeleted] [bit] NOT NULL,
  [DeleterUserId] [bigint] NULL,
  [DeletionTime] [datetime2](7) NULL,
  organizationId varchar(20)  NOT NULL,
  warehouseId varchar(20)  NOT NULL,
  asnNo varchar(20)  NOT NULL,
  asnLineNo int NOT NULL,
  customerId varchar(30)  NOT NULL,
  sku varchar(50)  NOT NULL,
  skuDescr varchar(500)  DEFAULT NULL,
  poNo varchar(20)  DEFAULT NULL,
  poLineNo int DEFAULT NULL,
  lineStatus varchar(2)  NOT NULL,
  receivedTime datetime NULL DEFAULT NULL,
  expectedQty decimal(18,8) NOT NULL,
  expectedQty_Each decimal(18,8) NOT NULL,
  receivedQty decimal(18,8) NOT NULL DEFAULT '0.00000000',
  receivedQty_Each decimal(18,8) NOT NULL DEFAULT '0.00000000',
  packId varchar(50)  DEFAULT NULL,
  packUom varchar(10)  NOT NULL,
  holdRejectCode varchar(2)  DEFAULT NULL,
  holdRejectReason varchar(60)  DEFAULT NULL,
  productStatus varchar(20)  DEFAULT NULL,
  productStatus_Descr varchar(60)  DEFAULT NULL,
  receivingLocation varchar(60)  DEFAULT NULL,
  containerId varchar(30)  DEFAULT NULL,
  lotAtt01 varchar(20)  DEFAULT NULL,
  lotAtt02 varchar(20)  DEFAULT NULL,
  lotAtt03 varchar(20)  DEFAULT NULL,
  lotAtt04 varchar(100)  DEFAULT NULL,
  lotAtt05 varchar(100)  DEFAULT NULL,
  lotAtt06 varchar(100)  DEFAULT NULL,
  lotAtt07 varchar(100)  DEFAULT NULL,
  lotAtt08 varchar(100)  DEFAULT NULL,
  lotAtt09 varchar(100)  DEFAULT NULL,
  lotAtt10 varchar(100)  DEFAULT NULL,
  lotAtt11 varchar(100)  DEFAULT NULL,
  lotAtt12 varchar(100)  DEFAULT NULL,
  lotAtt13 varchar(100)  DEFAULT NULL,
  lotAtt14 varchar(100)  DEFAULT NULL,
  lotAtt15 varchar(100)  DEFAULT NULL,
  lotAtt16 varchar(100)  DEFAULT NULL,
  lotAtt17 varchar(100)  DEFAULT NULL,
  lotAtt18 varchar(100)  DEFAULT NULL,
  lotAtt19 varchar(100)  DEFAULT NULL,
  lotAtt20 varchar(100)  DEFAULT NULL,
  lotAtt21 varchar(100)  DEFAULT NULL,
  lotAtt22 varchar(100)  DEFAULT NULL,
  lotAtt23 varchar(100)  DEFAULT NULL,
  lotAtt24 varchar(100)  DEFAULT NULL,
  totalCubic decimal(18,8) NOT NULL,
  totalGrossWeight decimal(18,8) NOT NULL,
  totalNetWeight decimal(18,8) NOT NULL,
  totalPrice decimal(24,8) NOT NULL DEFAULT '0.00000000',
  createSource varchar(35)  DEFAULT NULL,
  palletizeQty_Each decimal(18,8) DEFAULT NULL,
  palletizeMethod varchar(8)  DEFAULT NULL,
  planToLoc varchar(60)  DEFAULT NULL,
  reserve_Flag varchar(1)  NOT NULL DEFAULT 'N',
  alternativeSku varchar(100)  DEFAULT NULL,
  alternativeDescr varchar(200)  DEFAULT NULL,
  printLabel varchar(1)  DEFAULT NULL,
  damagedQty_Each decimal(18,8) DEFAULT NULL,
  rejectedQty decimal(18,8) DEFAULT NULL,
  rejectedQty_Each decimal(18,8) DEFAULT NULL,
  qcStatus varchar(2)  DEFAULT NULL,
  overRcvPercentage decimal(18,8) DEFAULT NULL,
  referenceLineNo int DEFAULT NULL,
  asnLineFilter varchar(100)  DEFAULT NULL,
  operator varchar(35)  DEFAULT NULL,
  preReceivedQty_Each decimal(18,8) DEFAULT NULL,
  preReceivedLocation varchar(60)  DEFAULT NULL,
  dedi01 varchar(200)  DEFAULT NULL,
  dedi02 varchar(200)  DEFAULT NULL,
  dedi03 varchar(200)  DEFAULT NULL,
  dedi04 varchar(200)  DEFAULT NULL,
  dedi05 varchar(200)  DEFAULT NULL,
  dedi06 varchar(200)  DEFAULT NULL,
  dedi07 varchar(200)  DEFAULT NULL,
  dedi08 varchar(200)  DEFAULT NULL,
  dedi09 decimal(18,8) DEFAULT NULL,
  dedi10 decimal(18,8) DEFAULT NULL,
  dedi11 varchar(200)  DEFAULT NULL,
  dedi12 varchar(200)  DEFAULT NULL,
  dedi13 varchar(200)  DEFAULT NULL,
  dedi14 varchar(200)  DEFAULT NULL,
  dedi15 varchar(200)  DEFAULT NULL,
  dedi16 varchar(200)  DEFAULT NULL,
  dedi17 varchar(200)  DEFAULT NULL,
  dedi18 varchar(200)  DEFAULT NULL,
  dedi19 varchar(200)  DEFAULT NULL,
  dedi20 varchar(200)  DEFAULT NULL,
  noteText text ,
  udf01 varchar(500)  DEFAULT NULL,
  udf02 varchar(500)  DEFAULT NULL,
  udf03 varchar(500)  DEFAULT NULL,
  udf04 varchar(500)  DEFAULT NULL,
  udf05 varchar(500)  DEFAULT NULL,
  udf06 varchar(500)  DEFAULT NULL,
  currentVersion int NOT NULL DEFAULT '100',
  oprSeqFlag varchar(65)  NOT NULL DEFAULT '2016',
  -- addWho varchar(40)  DEFAULT NULL,
  -- addTime datetime NULL DEFAULT NULL,
  -- editWho varchar(40)  DEFAULT NULL,
  -- editTime datetime NULL DEFAULT NULL,
  checkItemsFlag char(1)  DEFAULT NULL,
  erpCancelFlag char(1)  NOT NULL DEFAULT 'N',
  PRIMARY KEY (Id),
  INDEX auto_shard_key_organizationId (organizationId),
  INDEX I_DOC_ASN_DETAILS (organizationId,warehouseId,asnNo,asnLineNo),
  INDEX I_DOC_ASN_DETAILS_AE (organizationId,warehouseId,asnNo,expectedQty_Each),
  INDEX I_DOC_ASN_DETAILS_CSA (organizationId,warehouseId,customerId,asnNo,sku),
  INDEX I_DOC_ASN_DETAILS_OWAAL (organizationId,warehouseId,asnNo,asnLineNo,lineStatus),
  INDEX I_DOC_ASN_DETAILS_PP (organizationId,warehouseId,poNo,poLineNo),
  INDEX I_DOC_ASN_DETAILS_PU (organizationId,warehouseId,packId,packUom)
) ;






-- wms_ftest.doc_asn_header definition

DROP TABLE doc_asn_header; 
CREATE TABLE doc_asn_header (
  [Id] [int] IDENTITY(1,1) NOT NULL,
  [CreationTime] [datetime2](7) NOT NULL,
  [CreatorUserId] [bigint] NULL,
  [LastModificationTime] [datetime2](7) NULL,
  [LastModifierUserId] [bigint] NULL,
  [IsDeleted] [bit] NOT NULL,
  [DeleterUserId] [bigint] NULL,
  [DeletionTime] [datetime2](7) NULL,
  organizationId varchar(20)  NOT NULL,
  warehouseId varchar(20)  NOT NULL,
  asnNo varchar(20)  NOT NULL,
  asnType varchar(20)  DEFAULT NULL,
  asnStatus varchar(2)  NOT NULL,
  customerId varchar(30)  NOT NULL,
  asnCreationTime datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expectedArriveTime1 datetime NULL DEFAULT NULL,
  expectedArriveTime2 datetime NULL DEFAULT NULL,
  asnReference1 varchar(50)  DEFAULT NULL,
  asnReference2 varchar(50)  DEFAULT NULL,
  asnReference3 varchar(50)  DEFAULT NULL,
  asnReference4 varchar(50)  DEFAULT NULL,
  asnReference5 varchar(50)  DEFAULT NULL,
  door varchar(50)  DEFAULT NULL,
  carrierId varchar(30)  DEFAULT NULL,
  carrierName varchar(200)  DEFAULT NULL,
  carrierContact varchar(200)  DEFAULT NULL,
  carrierMail varchar(100)  DEFAULT NULL,
  carrierFax varchar(50)  DEFAULT NULL,
  carrierTel1 varchar(40)  DEFAULT NULL,
  carrierTel2 varchar(40)  DEFAULT NULL,
  carrierAddress1 varchar(200)  DEFAULT NULL,
  carrierAddress2 varchar(200)  DEFAULT NULL,
  carrierAddress3 varchar(100)  DEFAULT NULL,
  carrierAddress4 varchar(100)  DEFAULT NULL,
  carrierCity varchar(50)  DEFAULT NULL,
  carrierProvince varchar(50)  DEFAULT NULL,
  carrierCountry varchar(20)  DEFAULT NULL,
  carrierZip varchar(10)  DEFAULT NULL,
  countryOfOrigin varchar(2)  DEFAULT NULL,
  countryOfDestination varchar(2)  DEFAULT NULL,
  placeOfLoading varchar(60)  DEFAULT NULL,
  placeOfDischarge varchar(60)  DEFAULT NULL,
  placeOfDelivery varchar(60)  DEFAULT NULL,
  paymentTerms varchar(4)  DEFAULT NULL,
  paymentTermsDescr varchar(100)  DEFAULT NULL,
  deliveryTerms varchar(10)  DEFAULT NULL,
  deliveryTermsDescr varchar(100)  DEFAULT NULL,
  poNo varchar(20)  DEFAULT NULL,
  createSource varchar(35)  DEFAULT NULL,
  byTrace_Flag varchar(1)  NOT NULL DEFAULT 'N',
  reserve_Flag varchar(1)  NOT NULL DEFAULT 'N',
  receiveId bigint DEFAULT NULL,
  supplierId varchar(30)  DEFAULT NULL,
  supplierName varchar(200)  DEFAULT NULL,
  supplierContact varchar(200)  DEFAULT NULL,
  supplierMail varchar(100)  DEFAULT NULL,
  supplierFax varchar(50)  DEFAULT NULL,
  supplierTel1 varchar(40)  DEFAULT NULL,
  supplierTel2 varchar(40)  DEFAULT NULL,
  supplierAddress1 varchar(200)  DEFAULT NULL,
  supplierAddress2 varchar(200)  DEFAULT NULL,
  supplierAddress3 varchar(100)  DEFAULT NULL,
  supplierAddress4 varchar(100)  DEFAULT NULL,
  supplierCity varchar(50)  DEFAULT NULL,
  supplierProvince varchar(50)  DEFAULT NULL,
  supplierCountry varchar(20)  DEFAULT NULL,
  supplierZip varchar(10)  DEFAULT NULL,
  billingClass_Group varchar(10)  DEFAULT NULL,
  ediSendFlag varchar(1)  NOT NULL DEFAULT 'N',
  ediSendTime2 datetime NULL DEFAULT NULL,
  ediSendTime3 datetime NULL DEFAULT NULL,
  hedi01 varchar(200)  DEFAULT NULL,
  hedi02 varchar(200)  DEFAULT NULL,
  hedi03 varchar(200)  DEFAULT NULL,
  hedi04 varchar(200)  DEFAULT NULL,
  hedi05 varchar(200)  DEFAULT NULL,
  hedi06 varchar(200)  DEFAULT NULL,
  hedi07 varchar(200)  DEFAULT NULL,
  hedi08 varchar(200)  DEFAULT NULL,
  hedi09 decimal(18,8) DEFAULT NULL,
  hedi10 decimal(18,8) DEFAULT NULL,
  issuePartyId varchar(30)  DEFAULT NULL,
  issuePartyName varchar(200)  DEFAULT NULL,
  issuePartyContact varchar(200)  DEFAULT NULL,
  issuePartyMail varchar(100)  DEFAULT NULL,
  issuePartyFax varchar(50)  DEFAULT NULL,
  issuePartyTel1 varchar(40)  DEFAULT NULL,
  issuePartyTel2 varchar(40)  DEFAULT NULL,
  issuePartyAddress1 varchar(200)  DEFAULT NULL,
  issuePartyAddress2 varchar(200)  DEFAULT NULL,
  issuePartyAddress3 varchar(100)  DEFAULT NULL,
  issuePartyAddress4 varchar(100)  DEFAULT NULL,
  issuePartyCity varchar(50)  DEFAULT NULL,
  issuePartyProvince varchar(50)  DEFAULT NULL,
  issuePartyCountry varchar(2)  DEFAULT NULL,
  issuePartyZip varchar(10)  DEFAULT NULL,
  billingId varchar(30)  DEFAULT NULL,
  billingName varchar(200)  DEFAULT NULL,
  billingContact varchar(200)  DEFAULT NULL,
  billingMail varchar(100)  DEFAULT NULL,
  billingFax varchar(50)  DEFAULT NULL,
  billingTel1 varchar(40)  DEFAULT NULL,
  billingTel2 varchar(40)  DEFAULT NULL,
  billingAddress1 varchar(200)  DEFAULT NULL,
  billingAddress2 varchar(200)  DEFAULT NULL,
  billingAddress3 varchar(100)  DEFAULT NULL,
  billingAddress4 varchar(100)  DEFAULT NULL,
  billingCity varchar(50)  DEFAULT NULL,
  billingProvince varchar(50)  DEFAULT NULL,
  billingCountry varchar(20)  DEFAULT NULL,
  billingZip varchar(10)  DEFAULT NULL,
  asnPrintFlag varchar(1)  DEFAULT 'N',
  qcStatus varchar(2)  DEFAULT NULL,
  returnPrintFlag varchar(1)  DEFAULT 'N',
  zoneGroup varchar(20)  DEFAULT NULL,
  priority varchar(1)  DEFAULT NULL,
  releaseStatus varchar(1)  NOT NULL DEFAULT 'Y',
  packMaterialConsume varchar(1)  DEFAULT NULL,
  medicalXMLTime datetime NULL DEFAULT NULL,
  followUp varchar(20)  DEFAULT NULL,
  serialNoCatch varchar(1)  NOT NULL DEFAULT 'N',
  userDefineA varchar(20)  DEFAULT NULL,
  userDefineB varchar(20)  DEFAULT NULL,
  lastReceivingTime datetime NULL DEFAULT NULL,
  actualArriveTime datetime NULL DEFAULT NULL,
  archiveFlag varchar(1)  NOT NULL DEFAULT 'N',
  totalCubic decimal(18,8) NOT NULL DEFAULT '0.00000000',
  totalGrossWeight decimal(18,8) NOT NULL DEFAULT '0.00000000',
  totalNetWeight decimal(18,8) NOT NULL DEFAULT '0.00000000',
  totalPrice decimal(24,8) NOT NULL DEFAULT '0.00000000',
  totalLineCount int NOT NULL DEFAULT '0',
  curLineNo int NOT NULL DEFAULT '0',
  totalSkuCount int NOT NULL DEFAULT '0',
  noteText text,
  udf01 varchar(500)  DEFAULT NULL,
  udf02 varchar(500)  DEFAULT NULL,
  udf03 varchar(500)  DEFAULT NULL,
  udf04 varchar(500)  DEFAULT NULL,
  udf05 varchar(500)  DEFAULT NULL,
  udf06 varchar(500)  DEFAULT NULL,
  udf07 varchar(500)  DEFAULT NULL,
  udf08 varchar(500)  DEFAULT NULL,
  currentVersion int NOT NULL DEFAULT '100',
  oprSeqFlag varchar(65)  NOT NULL DEFAULT '2016',
  -- addWho varchar(40)  DEFAULT NULL,
  -- addTime datetime NULL DEFAULT NULL,
  -- editWho varchar(40)  DEFAULT NULL,
  -- editTime datetime NULL DEFAULT NULL,
  supplierDistrict varchar(50)  DEFAULT NULL,
  supplierStreet varchar(50)  DEFAULT NULL,
  carrierDistrict varchar(50)  DEFAULT NULL,
  carrierStreet varchar(50)  DEFAULT NULL,
  billingDistrict varchar(50)  DEFAULT NULL,
  billingStreet varchar(50)  DEFAULT NULL,
  issuePartyDistrict varchar(50)  DEFAULT NULL,
  issuePartyStreet varchar(50)  DEFAULT NULL,
  erpCancelFlag char(1)  DEFAULT 'N',
  erpCancelReason varchar(100)  DEFAULT NULL,
  ediSendTime datetime NULL DEFAULT NULL,
  ediErrorCode varchar(50)  DEFAULT NULL,
  ediErrorMessage text ,
  ediSendFlag2 char(1)  NOT NULL DEFAULT 'N',
  ediErrorCode2 varchar(50)  DEFAULT NULL,
  ediErrorMessage2 text ,
  ediSendFlag3 char(1)  NOT NULL DEFAULT 'N',
  ediErrorCode3 varchar(50)  DEFAULT NULL,
  ediErrorMessage3 text ,
  udf09 decimal(18,8) DEFAULT NULL,
  udf10 decimal(18,8) DEFAULT NULL,
  ocpNo varchar(50)  DEFAULT NULL,
  splitFlag char(1)  DEFAULT 'N',
  reverseAsnNo varchar(20)  DEFAULT NULL,
  orderSource varchar(10)  DEFAULT NULL,
  totalQty decimal(18,8) DEFAULT NULL,
  PRIMARY KEY (Id),
  INDEX auto_shard_key_organizationId (organizationId),
  INDEX I_DOC_ASN_HEADER (organizationId,warehouseId,asnNo),
  INDEX I_DOC_ASN_HEADER_ARCHIVEFLAG (organizationId,warehouseId,archiveFlag),
  INDEX I_DOC_ASN_HEADER_ASNS (organizationId,warehouseId,asnStatus),
  INDEX I_DOC_ASN_HEADER_EDI (organizationId,warehouseId,customerId,asnStatus),
  INDEX I_DOC_ASN_HEADER_EDIFLAG (organizationId,warehouseId,ediSendFlag,asnStatus),
  INDEX I_DOC_ASN_HEADER_Supplier (organizationId,supplierId),
  INDEX IDX_DOC_ASN_HEADER_CUSTOMERID (organizationId,warehouseId,customerId,asnStatus),
  INDEX IDX_DOC_ASN_HEADER_REF1 (organizationId,warehouseId,asnReference1)
) ;

-- wms_ftest.doc_asn_serialno definition

DROP TABLE doc_asn_serialno;
CREATE TABLE doc_asn_serialno (
  [Id] [int] IDENTITY(1,1) NOT NULL,
  [CreationTime] [datetime2](7) NOT NULL,
  [CreatorUserId] [bigint] NULL,
  [LastModificationTime] [datetime2](7) NULL,
  [LastModifierUserId] [bigint] NULL,
  [IsDeleted] [bit] NOT NULL,
  [DeleterUserId] [bigint] NULL,
  [DeletionTime] [datetime2](7) NULL,
  organizationId varchar(20)  NOT NULL,
  warehouseId varchar(20)  NOT NULL,
  asnNo varchar(20)  NOT NULL,
  serialNo varchar(40)  NOT NULL,
  sku varchar(50)  DEFAULT NULL,
  scanTime datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  customerId varchar(30)  DEFAULT NULL,
  locationId varchar(60)  DEFAULT NULL,
  traceId varchar(30)  DEFAULT NULL,
  stockFlag varchar(1)  NOT NULL DEFAULT 'N',
  lotNum varchar(10)  DEFAULT NULL,
  secondSerialNo varchar(40)  DEFAULT NULL,
  qty decimal(18,8) DEFAULT NULL,
  qcFlag char(1)  DEFAULT 'N',
  partialFlag varchar(1)  DEFAULT NULL,
  consigneeId varchar(30)  DEFAULT NULL,
  qcQty int DEFAULT NULL,
  grossWeight decimal(18,8) DEFAULT NULL,
  cubic decimal(18,8) DEFAULT NULL,
  cartonType varchar(50)  DEFAULT NULL,
  transactionId varchar(20)  DEFAULT NULL,
  noteText text ,
  udf01 varchar(500)  DEFAULT NULL,
  udf02 varchar(500)  DEFAULT NULL,
  udf03 varchar(500)  DEFAULT NULL,
  udf04 varchar(500)  DEFAULT NULL,
  udf05 varchar(500)  DEFAULT NULL,
  currentVersion int NOT NULL DEFAULT '100',
  oprSeqFlag varchar(65)  NOT NULL DEFAULT '2016',
  -- addWho varchar(40)  DEFAULT NULL,
  -- addTime datetime NULL DEFAULT NULL,
  -- editWho varchar(40)  DEFAULT NULL,
  -- editTime datetime NULL DEFAULT NULL,
  holdFlag char(1)  NOT NULL DEFAULT 'N',
  supplierId varchar(30)  DEFAULT NULL,
  originalCode varchar(40)  DEFAULT NULL,
  PRIMARY KEY (Id),
  INDEX auto_shard_key_organizationId (organizationId),
  INDEX i_DOC_ASN_SERIALNO (organizationId,warehouseId,asnNo,serialNo),
  INDEX i_DOC_ASN_SERIALNO_stockFlag (organizationId,warehouseId,asnNo,stockFlag),
  INDEX I_DOC_ASN_SERIALNO_T (organizationId,warehouseId,transactionId)
) ;







-- wms_ftest.doc_po_header definition
DROP TABLE doc_po_header;
CREATE TABLE doc_po_header (
  [Id] [int] IDENTITY(1,1) NOT NULL,
  [CreationTime] [datetime2](7) NOT NULL,
  [CreatorUserId] [bigint] NULL,
  [LastModificationTime] [datetime2](7) NULL,
  [LastModifierUserId] [bigint] NULL,
  [IsDeleted] [bit] NOT NULL,
  [DeleterUserId] [bigint] NULL,
  [DeletionTime] [datetime2](7) NULL,
  organizationId varchar(20)  NOT NULL,
  warehouseId varchar(20)  NOT NULL,
  poNo varchar(20)  NOT NULL,
  poType varchar(20)  NOT NULL,
  poStatus varchar(2)  NOT NULL,
  customerId varchar(30)  DEFAULT NULL,
  poCreationTime datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expectedArriveTime1 datetime NULL DEFAULT NULL,
  expectedArriveTime2 datetime NULL DEFAULT NULL,
  poReference1 varchar(50)  DEFAULT NULL,
  poReference2 varchar(50)  DEFAULT NULL,
  poReference3 varchar(50)  DEFAULT NULL,
  poReference4 varchar(50)  DEFAULT NULL,
  poReference5 varchar(50)  DEFAULT NULL,
  supplierId varchar(30)  DEFAULT NULL,
  supplier_Name varchar(200)  DEFAULT NULL,
  supplier_Address1 varchar(200)  DEFAULT NULL,
  supplier_Address2 varchar(200)  DEFAULT NULL,
  supplier_Address3 varchar(100)  DEFAULT NULL,
  supplier_Address4 varchar(100)  DEFAULT NULL,
  supplier_City varchar(50)  DEFAULT NULL,
  supplier_Province varchar(50)  DEFAULT NULL,
  supplier_Country varchar(20)  DEFAULT NULL,
  supplier_Zip varchar(10)  DEFAULT NULL,
  supplier_contact varchar(200)  DEFAULT NULL,
  supplier_Mail varchar(100)  DEFAULT NULL,
  supplier_Fax varchar(50)  DEFAULT NULL,
  supplier_Tel1 varchar(40)  DEFAULT NULL,
  supplier_Tel2 varchar(40)  DEFAULT NULL,
  hedi01 varchar(200)  DEFAULT NULL,
  hedi02 varchar(200)  DEFAULT NULL,
  hedi03 varchar(200)  DEFAULT NULL,
  hedi04 varchar(200)  DEFAULT NULL,
  hedi05 varchar(200)  DEFAULT NULL,
  hedi06 varchar(200)  DEFAULT NULL,
  hedi07 varchar(200)  DEFAULT NULL,
  hedi08 varchar(200)  DEFAULT NULL,
  hedi09 decimal(18,8) DEFAULT NULL,
  hedi10 decimal(18,8) DEFAULT NULL,
  ediSendTime datetime NULL DEFAULT NULL,
  ediSendFlag char(1)  NOT NULL DEFAULT 'N',
  createSource varchar(35)  DEFAULT NULL,
  releaseStatus char(1)  NOT NULL DEFAULT 'N',
  userDefineA varchar(20)  DEFAULT NULL,
  userDefineB varchar(20)  DEFAULT NULL,
  asnLinked char(1)  NOT NULL DEFAULT 'N',
  totalCubic decimal(18,8) NOT NULL DEFAULT '0.00000000',
  totalGrossWeight decimal(18,8) NOT NULL DEFAULT '0.00000000',
  totalNetWeight decimal(18,8) NOT NULL DEFAULT '0.00000000',
  totalPrice decimal(24,8) NOT NULL DEFAULT '0.00000000',
  totalLineCount int NOT NULL DEFAULT '0',
  curLineNo int NOT NULL DEFAULT '0',
  totalSkuCount int NOT NULL DEFAULT '0',
  noteText text ,
  udf01 varchar(500)  DEFAULT NULL,
  udf02 varchar(500)  DEFAULT NULL,
  udf03 varchar(500)  DEFAULT NULL,
  udf04 varchar(500)  DEFAULT NULL,
  udf05 varchar(500)  DEFAULT NULL,
  currentVersion int NOT NULL DEFAULT '100',
  oprSeqFlag varchar(65)  NOT NULL DEFAULT '2016',
  -- addWho varchar(40)  DEFAULT NULL,
  -- addTime datetime NULL DEFAULT NULL,
  -- editWho varchar(40)  DEFAULT NULL,
  -- editTime datetime NULL DEFAULT NULL,
  supplier_District varchar(50)  DEFAULT NULL,
  supplier_Street varchar(50)  DEFAULT NULL,
  issuePartyId varchar(30)  DEFAULT NULL,
  issuePartyName varchar(200)  DEFAULT NULL,
  issuePartyContact varchar(200)  DEFAULT NULL,
  issuePartyMail varchar(100)  DEFAULT NULL,
  issuePartyFax varchar(50)  DEFAULT NULL,
  issuePartyTel1 varchar(50)  DEFAULT NULL,
  issuePartyTel2 varchar(40)  DEFAULT NULL,
  issuePartyAddress1 varchar(200)  DEFAULT NULL,
  issuePartyAddress2 varchar(200)  DEFAULT NULL,
  issuePartyAddress3 varchar(100)  DEFAULT NULL,
  issuePartyAddress4 varchar(100)  DEFAULT NULL,
  issuePartyCity varchar(50)  DEFAULT NULL,
  issuePartyProvince varchar(50)  DEFAULT NULL,
  issuePartyCountry varchar(2)  DEFAULT NULL,
  issuePartyZip varchar(10)  DEFAULT NULL,
  udf06 varchar(500)  DEFAULT NULL,
  udf07 varchar(500)  DEFAULT NULL,
  udf08 varchar(500)  DEFAULT NULL,
  issuePartyDistrict varchar(50)  DEFAULT NULL,
  issuePartyStreet varchar(50)  DEFAULT NULL,
  reversePoNo varchar(20)  DEFAULT NULL,
  erpCancelFlag char(1)  DEFAULT 'N',
  erpCancelReason varchar(100)  DEFAULT NULL,
  PRIMARY KEY (Id),
  INDEX auto_shard_key_organizationId (organizationId),
  INDEX I_DOC_PO_HEADER(organizationId,warehouseId,poNo),
  INDEX I_DOC_PO_HEADER_C (organizationId,warehouseId,customerId)
) ;






-- wms_ftest.doc_po_details definition
DROP TABLE doc_po_details;
CREATE TABLE doc_po_details (
  [Id] [int] IDENTITY(1,1) NOT NULL,
  [CreationTime] [datetime2](7) NOT NULL,
  [CreatorUserId] [bigint] NULL,
  [LastModificationTime] [datetime2](7) NULL,
  [LastModifierUserId] [bigint] NULL,
  [IsDeleted] [bit] NOT NULL,
  [DeleterUserId] [bigint] NULL,
  [DeletionTime] [datetime2](7) NULL,
  organizationId varchar(20)  NOT NULL,
  warehouseId varchar(20)  NOT NULL,
  poNo varchar(20)  NOT NULL,
  poLineNo int NOT NULL,
  poLineStatus varchar(2)  NOT NULL,
  customerId varchar(30)  DEFAULT NULL,
  sku varchar(50)  NOT NULL,
  skuDescr varchar(500)  DEFAULT NULL,
  orderedQty decimal(18,8) NOT NULL,
  orderedQty_Each decimal(18,8) NOT NULL,
  receivedQty decimal(18,8) NOT NULL DEFAULT '0.00000000',
  receivedQty_Each decimal(18,8) NOT NULL DEFAULT '0.00000000',
  receivedTime datetime NULL DEFAULT NULL,
  packId varchar(50)  DEFAULT NULL,
  packUom varchar(10)  NOT NULL,
  totalCubic decimal(18,8) NOT NULL DEFAULT '0.00000000',
  totalGrossWeight decimal(18,8) NOT NULL DEFAULT '0.00000000',
  totalNetWeight decimal(18,8) NOT NULL DEFAULT '0.00000000',
  totalPrice decimal(24,8) NOT NULL DEFAULT '0.00000000',
  lotAtt01 varchar(20)  DEFAULT NULL,
  lotAtt02 varchar(20)  DEFAULT NULL,
  lotAtt03 varchar(20)  DEFAULT NULL,
  lotAtt04 varchar(100)  DEFAULT NULL,
  lotAtt05 varchar(100)  DEFAULT NULL,
  lotAtt06 varchar(100)  DEFAULT NULL,
  lotAtt07 varchar(100)  DEFAULT NULL,
  lotAtt08 varchar(100)  DEFAULT NULL,
  lotAtt09 varchar(100)  DEFAULT NULL,
  lotAtt10 varchar(100)  DEFAULT NULL,
  lotAtt11 varchar(100)  DEFAULT NULL,
  lotAtt12 varchar(100)  DEFAULT NULL,
  lotAtt13 varchar(100)  DEFAULT NULL,
  lotAtt14 varchar(100)  DEFAULT NULL,
  lotAtt15 varchar(100)  DEFAULT NULL,
  lotAtt16 varchar(100)  DEFAULT NULL,
  lotAtt17 varchar(100)  DEFAULT NULL,
  lotAtt18 varchar(100)  DEFAULT NULL,
  lotAtt19 varchar(100)  DEFAULT NULL,
  lotAtt20 varchar(100)  DEFAULT NULL,
  lotAtt21 varchar(100)  DEFAULT NULL,
  lotAtt22 varchar(100)  DEFAULT NULL,
  lotAtt23 varchar(100)  DEFAULT NULL,
  lotAtt24 varchar(100)  DEFAULT NULL,
  dedi01 varchar(200)  DEFAULT NULL,
  dedi02 varchar(200)  DEFAULT NULL,
  dedi03 varchar(200)  DEFAULT NULL,
  dedi04 varchar(200)  DEFAULT NULL,
  dedi05 varchar(200)  DEFAULT NULL,
  dedi06 varchar(200)  DEFAULT NULL,
  dedi07 varchar(200)  DEFAULT NULL,
  dedi08 varchar(200)  DEFAULT NULL,
  dedi09 decimal(18,8) DEFAULT NULL,
  dedi10 decimal(18,8) DEFAULT NULL,
  qtyReleased decimal(18,8) DEFAULT '0.00000000',
  price decimal(24,8) DEFAULT NULL,
  noteText text ,
  udf01 varchar(500)  DEFAULT NULL,
  udf02 varchar(500)  DEFAULT NULL,
  udf03 varchar(500)  DEFAULT NULL,
  udf04 varchar(500)  DEFAULT NULL,
  udf05 varchar(500)  DEFAULT NULL,
  currentVersion int NOT NULL DEFAULT '100',
  oprSeqFlag varchar(65)  NOT NULL DEFAULT '2016',
  -- addWho varchar(40)  DEFAULT NULL,
  -- addTime datetime NULL DEFAULT NULL,
  -- editWho varchar(40)  DEFAULT NULL,
  -- editTime datetime NULL DEFAULT NULL,
  dedi11 varchar(200)  DEFAULT NULL,
  dedi12 varchar(200)  DEFAULT NULL,
  dedi13 varchar(200)  DEFAULT NULL,
  dedi14 varchar(200)  DEFAULT NULL,
  dedi15 varchar(200)  DEFAULT NULL,
  dedi16 varchar(200)  DEFAULT NULL,
  dedi17 varchar(200)  DEFAULT NULL,
  dedi18 varchar(200)  DEFAULT NULL,
  dedi19 varchar(200)  DEFAULT NULL,
  dedi20 varchar(200)  DEFAULT NULL,
  erpCancelFlag char(1)  DEFAULT 'N',
  erpCancelReason varchar(100)  DEFAULT NULL,
  cancelledQty decimal(18,8) DEFAULT NULL,
  cancelledQtyMemo text ,
  containerId varchar(30)  DEFAULT NULL,
  PRIMARY KEY (Id),
  INDEX auto_shard_key_organizationId (organizationId),
  INDEX I_DOC_PO_DETAILS (organizationId,warehouseId,poNo,poLineNo),
  INDEX I_DOC_PO_DETAILS_PCS (organizationId,warehouseId,poNo,sku,customerId),
  INDEX I_DOC_PO_DETAILS_PU (organizationId,warehouseId,packId,packUom)
) ;













